name: generate github-contribution-grid-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/output/github-contribution-grid-snake.svg
            dist/output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the generated snake svg to the output directory on master branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: master
          build_dir: dist/output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}